### ISSUE TITLE
Incorrect accuracy estimation 

### ISSUE THREAD

**Issue by kuzaleks** [AndreiLukashevich/Laba1_CMM#1]
I am concerned with the way you perform the actual recognition:

```
for i in range(int(len(corpus['n']))):
    xa_a = corpus['a'][i]
    xn_a = corpus['n'][i]
    if model_a.score(xa_a) > model_a.score(xn_a):
        a_true += 1
    else:
        a_false += 1
```

The main idea of the recognition is that you evaluate the probability of the SAME vector using both models. And based on relation of scores make a decision whether the phoneme is recognized correct or not:

```
for i in range(len(corpus['n'])):
    x = corpus['n'][i]
    if model_n.score(x) > model_a.score(x):
        n_correct += 1

acc = float(n_correct) / len(corpus['n'])
``` 

And the same for the phoneme `a`.

**Comment by AndreiLukashevich** [comment]
I fixed bug "Incorrect accuracy estimation".
