### ISSUE TITLE
The same data is used for both training and testing

### ISSUE THREAD

**Issue by kuzaleks** [AndreiLukashevich/Laba1_CMM#2]
The key requirement to trained model is to perform well on the data that it haven't seen before (that was not used for it's training).
In your app you use 80% of data for training and than all the 100% for testing. It means that all the training data participate in testing. It's wrong. 
You task is to evaluate the recognition accuracy only on the remaining 20% of data that was NOT used for training.

**Comment by AndreiLukashevich** [comment]
I fixed bug (The same data is used for both training and testing).
